#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=6

# fez keeps credentials in the macOS keychain, not dotfiles — same custody
# pattern as fez-keys. Everything this wizard captures lands under one
# service, readable later by build-signed.sh via `security find-generic-password`.
KC_SERVICE="fez-notary"
store_kc() {
  security add-generic-password -U -s "$KC_SERVICE" -a "$1" -w "$2" >/dev/null
  printf '  %s✓ keychain%s %s / %s\n' "$GREEN" "$RESET" "$KC_SERVICE" "$1"
}

banner "fez-desktop signing setup (Developer ID + notarization)"

# ── 1 · CSR ───────────────────────────────────────────────────────────────
stage "Create a certificate signing request (CSR)"
say "Keychain Access generates your signing keypair and a request file."
{ open -a "Keychain Access" >/dev/null 2>&1; } || warn "open Keychain Access manually (Spotlight → Keychain Access)"
step "Menu bar: Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority…"
say ""
say "  Fill the form EXACTLY like this:"
step "User Email Address:  your Apple ID email"
step "Common Name:         fez signing   (any name works)"
step "CA Email Address:    LEAVE EMPTY"
step "Request is:          ● Saved to disk   ← select this radio button FIRST"
say "                       (NOT 'Emailed to the CA' — that's the default trap)"
step "Continue → save the file to your Desktop (default name is fine)."
pause "Press Enter once the file is saved…"
CSR=$(ls -t "$HOME"/Desktop/*.certSigningRequest "$HOME"/Downloads/*.certSigningRequest "$HOME"/Documents/*.certSigningRequest 2>/dev/null | head -1 || true)
if [[ -n "$CSR" ]]; then
  say "found: $CSR"
else
  warn "no .certSigningRequest found on Desktop/Downloads/Documents."
  ask CSR "Path to the saved CSR file (or redo the steps above, then paste the path):"
fi

# ── 2 · portal certificate ────────────────────────────────────────────────
stage "Mint the Developer ID Application certificate"
open_url "https://developer.apple.com/account/resources/certificates/add"
step "Under 'Software', select 'Developer ID Application', then Continue."
step "Profile Type: keep the default (G2 Sub-CA). Upload the CSR from your Desktop."
step "Continue → Download. The .cer lands in ~/Downloads."
pause "Press Enter once it's downloaded…"

# ── 3 · install + verify ──────────────────────────────────────────────────
stage "Install the certificate and read your identity"
CER=$(ls -t "$HOME"/Downloads/developerID*.cer 2>/dev/null | head -1 || true)
if [[ -z "$CER" ]]; then
  ask CER_PATH "Path to the downloaded .cer file:"
  CER="$CER_PATH"
fi
say "importing: $CER"
security import "$CER" -k "$HOME/Library/Keychains/login.keychain-db" >/dev/null 2>&1 || note "already imported — fine"
if ! security find-identity -v -p codesigning | grep -q "Developer ID Application"; then
  say "identity not valid yet — fetching Apple's Developer ID G2 intermediate…"
  curl -fsSL -o /tmp/DeveloperIDG2CA.cer "https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer"
  security import /tmp/DeveloperIDG2CA.cer -k "$HOME/Library/Keychains/login.keychain-db" >/dev/null 2>&1 || true
fi
IDENTITY_LINE=$(security find-identity -v -p codesigning | grep -m1 "Developer ID Application" || true)
if [[ -z "$IDENTITY_LINE" ]]; then
  warn "no valid 'Developer ID Application' identity found. Two usual causes:"
  note "  - the CSR was made on a different Mac (private key lives there)"
  note "  - the intermediate cert is missing; re-run this wizard"
  exit 1
fi
SIGNING_IDENTITY=$(printf '%s' "$IDENTITY_LINE" | sed 's/.*"\(.*\)".*/\1/')
TEAM_ID=$(printf '%s' "$SIGNING_IDENTITY" | sed 's/.*(\(.*\))/\1/')
say "identity: $SIGNING_IDENTITY"
say "team id:  $TEAM_ID"

# ── 4 · app-specific password ─────────────────────────────────────────────
stage "Generate an app-specific password (for notarytool)"
say "Notarization signs in as you, but never with your real password."
open_url "https://account.apple.com/account/manage"
step "Sign in → 'Sign-In and Security' → 'App-Specific Passwords' → '+'."
step "Name it 'fez-notary'. Copy the generated password (xxxx-xxxx-xxxx-xxxx)."
ask_secret APP_PW "Paste the app-specific password:"
ask APPLE_ID_INPUT "Apple ID email [kennethxashley@gmail.com]:"
APPLE_ID="${APPLE_ID_INPUT:-kennethxashley@gmail.com}"

# ── 5 · store in the keychain ─────────────────────────────────────────────
stage "Store credentials (keychain service: $KC_SERVICE)"
store_kc "apple-id" "$APPLE_ID"
store_kc "password" "$APP_PW"
store_kc "team-id" "$TEAM_ID"
store_kc "identity" "$SIGNING_IDENTITY"

# ── 6 · prove it works ────────────────────────────────────────────────────
stage "Validate against Apple's notary service"
say "Asking notarytool for your submission history (empty is fine — success"
say "means the credentials are valid)."
if xcrun notarytool history --apple-id "$APPLE_ID" --password "$APP_PW" --team-id "$TEAM_ID" >/dev/null 2>&1; then
  printf '  %s✓ notary credentials verified%s\n' "$GREEN" "$RESET"
else
  warn "notarytool rejected the credentials. Usual causes:"
  note "  - password pasted with spaces, or a regular password instead of app-specific"
  note "  - Developer Program membership not fully active yet (can lag the email)"
  note "Re-run this wizard; stored keychain values update in place."
  exit 1
fi
pause "Done — press Enter for the summary."

finish
note "next: tell Claude the wizard finished — it wires signing into the build."
