import { invoke } from "@tauri-apps/api/core";
import type { KeptTool } from "./tools";

/**
 * Crystallize's top rung: turn a kept tool into a real, publishable
 * @fezchat extension on disk. The gui part is PLAIN JS — it uses the
 * `api.React` and `api.client.runQuery` every extension already gets, so
 * there's nothing to bundle. It renders the tool in a sandboxed iframe
 * with the same read bridge loom uses, wired through `api.client`.
 *
 * Exported tools are read-only for now (query + subscribe); write-back
 * needs the host consent prompt, which an extension can't yet raise.
 */

function slugify(title: string): string {
  const s = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
  return s || "tool";
}

/** The tool body wrapped with a READ-ONLY fez shim + a no-network CSP —
 * the same sandbox as loom's live tools, minus the write path. */
function wrapReadOnlyDoc(body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; font-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'">
<script>
(function(){
  var seq=0, pending={}, subs={};
  window.fez = {
    query: function(q){ return new Promise(function(res,rej){ var id=++seq; pending[id]={res:res,rej:rej}; parent.postMessage({__fez:1,type:'query',id:id,q:String(q)},'*'); }); },
    subscribe: function(q, cb){ var id=++seq; subs[id]=cb; parent.postMessage({__fez:1,type:'subscribe',id:id,q:String(q)},'*'); return function(){ delete subs[id]; parent.postMessage({__fez:1,type:'unsubscribe',id:id},'*'); }; }
  };
  window.addEventListener('message', function(e){
    var m=e.data; if(!m||m.__fezhost!==1) return;
    if(m.type==='result'){ var p=pending[m.id]; if(p){ delete pending[m.id]; m.error? p.rej(new Error(m.error)) : p.res(m.rows); } }
    else if(m.type==='update'){ var cb=subs[m.id]; if(cb){ try{ cb(m.rows, m.error?new Error(m.error):null); }catch(_){} } }
  });
})();
</script>
</head><body>${body}</body></html>`;
}

/** The plain-JS gui part: registers a settings panel that renders the tool
 * with a read bridge backed by api.client.runQuery. Self-contained — no
 * imports, no build step. */
function guiModule(title: string, doc: string): string {
  return `// Generated by loom — a fez tool as a gui extension.
export default function activate(api) {
  const React = api.React;
  const h = React.createElement;
  const TITLE = ${JSON.stringify(title)};
  const DOC = ${JSON.stringify(doc)};
  function Tool() {
    const ref = React.useRef(null);
    React.useEffect(function () {
      const frame = ref.current;
      if (!frame) return;
      const timers = new Map();
      const post = function (m) { if (frame.contentWindow) frame.contentWindow.postMessage(Object.assign({ __fezhost: 1 }, m), "*"); };
      const run = async function (qs) {
        try { return { rows: await api.client.runQuery(api.parseQuery(qs)) }; }
        catch (e) { return { error: String((e && e.message) || e) }; }
      };
      const onMsg = function (e) {
        if (e.source !== frame.contentWindow) return;
        const m = e.data;
        if (!m || m.__fez !== 1 || typeof m.id !== "number") return;
        if (m.type === "query") { run(m.q || "").then(function (r) { post(Object.assign({ type: "result", id: m.id }, r)); }); }
        else if (m.type === "subscribe") {
          const id = m.id, qs = m.q || "";
          const tick = function () { run(qs).then(function (r) { post(Object.assign({ type: "update", id: id }, r)); }); };
          tick();
          timers.set(id, setInterval(tick, 4000));
        } else if (m.type === "unsubscribe") {
          const t = timers.get(m.id);
          if (t) { clearInterval(t); timers.delete(m.id); }
        }
      };
      window.addEventListener("message", onMsg);
      return function () { window.removeEventListener("message", onMsg); timers.forEach(function (t) { clearInterval(t); }); };
    }, []);
    return h("iframe", { ref: ref, sandbox: "allow-scripts", srcDoc: DOC, style: { width: "100%", height: "72vh", border: 0, background: "#fff", borderRadius: "8px" } });
  }
  api.registerSettingsPanel(TITLE, function () { return h(Tool); });
}
`;
}

function packageJson(slug: string, title: string): string {
  return JSON.stringify(
    {
      name: `fez-tool-${slug}`,
      version: "0.1.0",
      description: `${title} — a fez tool exported from loom.`,
      type: "module",
      fez: { type: "extension", parts: { gui: "dist/gui.js" }, permissions: ["ui", "read:channels"] },
      files: ["dist"],
    },
    null,
    2
  ) + "\n";
}

function readme(slug: string, title: string): string {
  return `# fez-tool-${slug}

**${title}** — a live tool, exported from loom as a real fez extension.

It renders a sandboxed view backed by the fez read bridge (\`window.fez.query\` /
\`fez.subscribe\`, read-only, no network). The gui part is plain JS — no build.

## Share it

Publish to npm, then anyone installs it from **⊞ extensions → browse** (or
\`fez install <name>\`). It surfaces as a settings panel named "${title}".

\`\`\`
npm publish --access public
\`\`\`

Rename \`fez-tool-${slug}\` to your own scope first if you like.
`;
}

/** Write the package to ~/fez-tools/<slug>. Returns its path. */
export async function exportTool(tool: KeptTool): Promise<string> {
  const slug = slugify(tool.title);
  const doc = wrapReadOnlyDoc(tool.content);
  return invoke<string>("export_tool", {
    slug,
    guiJs: guiModule(tool.title, doc),
    pkgJson: packageJson(slug, tool.title),
    readme: readme(slug, tool.title),
  });
}
