import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Publishing is explicit. Never replace the descriptor pin on a failed build.
const tag = process.argv[2];
if (!tag || !/^ghcr\.io\/[a-z0-9_-]+\/[a-z0-9_.-]+:[A-Za-z0-9_.-]+$/.test(tag)) {
  throw new Error('Usage: npm run image:publish -- ghcr.io/OWNER/gradients-miner:TAG');
}
const root = fileURLToPath(new URL('../', import.meta.url));
const scratch = mkdtempSync(join(tmpdir(), 'fez-gradients-image-'));
try {
  const metadata = join(scratch, 'metadata.json');
  execFileSync('docker', ['buildx', 'build', '--platform', 'linux/amd64', '--push', '--metadata-file', metadata, '--tag', tag, '.'], { cwd: root, stdio: 'inherit' });
  const digest = JSON.parse(readFileSync(metadata, 'utf8'))['containerimage.digest'];
  if (!/^sha256:[a-f0-9]{64}$/.test(digest ?? '')) throw new Error('Build returned no valid image digest; descriptor unchanged');
  const image = `${tag.slice(0, tag.lastIndexOf(':'))}@${digest}`;
  writeFileSync(join(root, 'src/image.ts'), `// Generated by scripts/publish-image.mjs after a successful build and push.\nexport const image = ${JSON.stringify(image)};\n`);
  execFileSync('npm', ['run', 'build'], { cwd: root, stdio: 'inherit' });
  console.log(`Published and pinned ${image}. No miner was registered or started.`);
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
